version: '3.3'
volumes:
  static_value:
  media_value:
  db_value:

# networks:
#   myNetwork:

services:
  # Контейнер с базой данных
  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      # - ./postgres:/var/lib/postgresql/data
      - db_value:/var/lib/postgresql/data/
    expose:
      - '5432'
    restart: always
    env_file:
      - ./.env
    # networks:
    #   - myNetwork

  # Контейнер с приложением
  web:
    container_name: web
    build: ../foodgram/
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    # networks:
    #   - myNetwork

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - web
    # networks:
    #   - myNetwork

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    # networks:
    #   - myNetwork

  # Контейнер с pgadmin
  # pgadmin:
  #   container_name: pgadmin
  #   depends_on:
  #     - db
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: saminter@ya.ru
  #     PGADMIN_DEFAULT_PASSWORD: qwertyuiop
  #   ports:
  #     - "81:80"
  #   # expose:
  #   #   - '81'
  #   restart: always
  #   # networks:
  #   #   - myNetwork
