version: '3.3'
volumes:
  static_value:
  media_value:
  db_value:
  redoc:

services:
  # Контейнер с базой данных
  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      # - ./postgres:/var/lib/postgresql/data
      - db_value:/var/lib/postgresql/data/
    expose:
      - '5432'
    restart: always
    env_file:
      - ./.env

  web:
    container_name: web
    # image: saminter22/foodgram:latest
    image: saminter22/foodgram
    # build: ../foodgram/
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    # image: saminter22/foodgram_frontend:latest
    image: saminter22/foodgram_frontend
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    # image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
    restart: always
