# Generated by Django 2.2.19 on 2023-01-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_auto_20230127_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', to='dish.Tag', verbose_name='Теги'),
        ),
    ]
