name: Foodgram-workflow

on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        # обновление pip
        python -m pip install --upgrade pip 
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        cd foodgram
        pip install -r requirements.txt
    - name: Test with flake8
      run: |
        python -m flake8 foodgram
        # flake8 .
        #python -m pytest
        # pytest .
        # перейти в папку, содержащую manage.py — 
        #<корневая_папка_infra_actions>/<папка_проекта>/manage.py
        # cd api_yamdb/
    